name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  simple_animations: ^5.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  uuid: ^4.4.0
  percent_indicator: ^4.2.5
  image_picker: ^1.1.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flex_color_picker: ^3.5.1
  flutter_colorpicker: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  fl_chart: ^1.1.1
  rive: ^0.13.4
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  json_annotation: ^4.9.0
  syncfusion_flutter_gauges: ^31.2.12
  path: ^1.9.0
  smooth_page_indicator: ^1.1.0
  freezed_annotation: ^2.4.4
  table_calendar: ^3.1.2
  http: ^1.2.1
  flutter_html: ^3.0.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  timeline_tile: ^2.0.0
  permission_handler: ^12.0.1
  phosphor_flutter: ^2.1.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/acuario/
    - assets/icons/
    - assets/luna_png/
    - assets/marcos/
